version: '3'

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/postgres
      - SPRING_DATASOURCE_USERNAME=my_user
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    command: sh -c "cp -r /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps && cp -r /usr/local/tomcat/conf/context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml && catalina.sh run"
  db:
    image: 'postgres:13.1-alpine'
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres-data:




