version: '3'

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/postgres
      - SPRING_DATASOURCE_USERNAME=my_user
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.1-alpine'
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:




